capybara/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

core/urls.py
from django.urls import path

from .views import HomeView, AuthorizeView, CallbackView

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('authorize/', AuthorizeView.as_view(), name='authorize'),
    path('callback/', CallbackView.as_view(), name='callback'),
]

core/models.py
import uuid

from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

core/forms.py
from django import forms


class AuthorizeForm(forms.Form):
    subdomain = forms.CharField(max_length=100)

core/views.py
import random
from urllib.parse import urlencode
from uuid import uuid4

from django.conf import settings
from django.http.request import HttpRequest
from django.http.response import HttpResponse, HttpResponseBadRequest, HttpResponseRedirect
from django.urls import reverse
from django.views.generic import TemplateView, View

from .forms import AuthorizeForm


class HomeView(TemplateView):
    template_name = 'core/home.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['image'] = random.choice([
            'https://media.giphy.com/media/QOYjGrYSuBMAg/giphy.gif',
            'https://media.giphy.com/media/9Si6HlM5DfsA0/giphy.gif',
            'https://media.giphy.com/media/pejdqIYGcxHMY/giphy.gif',
        ])

        return context_data


class AuthorizeView(View):
    @staticmethod
    def post(request: HttpRequest) -> HttpResponse:
        form = AuthorizeForm(request.POST)

        if not form.is_valid():
            return HttpResponseBadRequest('Form is not valid')

        subdomain = form.cleaned_data['subdomain']

        url = f'https://{subdomain}.myshopify.com/admin/oauth/authorize?' + urlencode({
            'client_id': settings.SHOPIFY_API_KEY,
            'scope': 'read_products,read_orders',
            'redirect_uri': request.build_absolute_uri(reverse('core:callback')),
            'state': uuid4(),
        })

        return HttpResponseRedirect(url)


class CallbackView(View):
    @staticmethod
    def get(request: HttpRequest) -> HttpResponse:
        return HttpResponse('Hello, Callback!')

core/templates/core/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous">

    <title>Capybara</title>
</head>
<body>

<header class="container text-center my-5">
    <h1 class="h3">Capybara Shopify App</h1>
</header>

{% block content %}{% endblock %}

</body>
</html>

core/templates/core/home.html
{% extends 'core/base.html' %}

{% block content %}
    <main class="container text-center my-5">
        <div class="row">
            <div class="col-12 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
                <form method="post" action="{% url 'core:authorize' %}">
                    {% csrf_token %}
                    <div class="input-group">
                        <input type="text" name="subdomain" class="form-control">
                        <div class="input-group-append">
                            <span class="input-group-text">.myshopify.com</span>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary btn-block mt-3">Install</button>
                </form>
            </div>
        </div>
        <div class="mt-3">
            <img src="{{ image }}" alt="" class="img-fluid">
        </div>
    </main>
{% endblock %}